theme: jekyll-theme-cayman
title: Abstractive Turkish Text Summarization and CrossLingual Summarization Using Transformer
description: The study was done by Eymen Kağan Taşpınar, Yusuf Burak Yetiş and Onur Cihan. We share the results obtained from the models we mentioned in our study, which was published in Deep Learning Research Applications for Natural Language Processing book.
